export type TrendSource = { id:number; title:string; url:string|null; excerpt:string|null; content:string|null; createdAt:string; origin?:"MOA"|"DAILY_DESK"|"WEB_RESEARCH"; categoryHint?:TrendCategory };
export type TrendCategory = "technology"|"market"|"company"|"policy";
export type TrendEvidence = { id:number; title:string; url:string|null; origin:"MOA"|"DAILY_DESK"|"WEB_RESEARCH"; createdAt:string; publisher:string };
export type TrendIssue = { id:string; headline:string; summary:string; introduction:string; body:string; implications:string; metrics:string[]; companies:string[]; technologies:string[]; sources:TrendEvidence[] };

const LABELS:Record<TrendCategory,string>={technology:"기술 발전동향",market:"글로벌 시장동향",company:"주요 기업동향",policy:"정책·규제동향"};
const TERMS:Record<TrendCategory,string[]>={
 technology:["npu","ai 반도체","ai 가속기","tops","전력효율","추론","hbm","칩렛","cxl","공정","아키텍처","성능","메모리"],
 market:["시장규모","시장 규모","점유율","매출","출하량","투자액","cagr","성장률","전망","수요","공급","가격","판매","생산능력","증설","데이터센터 투자","채택","도입","capacity","demand","revenue","shipment","adoption"],
 company:["수주","양산","투자유치","투자 유치","공급계약","공급 계약","협력","인수","출시","계약","파트너십","funding","acquisition"],
 policy:["정책","규제","법안","예산","시행","ai act","regulation","법률","g7","oecd"]};
const COMPANIES=["MangoBoost","망고부스트","리벨리온","퓨리오사AI","딥엑스","사피온","엔비디아","NVIDIA","AMD","인텔","Intel","삼성전자","SK하이닉스","TSMC","브로드컴","퀄컴","마이크론","구글","Amazon","AWS","Microsoft","Meta"];
const TECHNOLOGIES=["NPU","AI 반도체","AI 가속기","GPU","HBM","HBM3E","HBM4","CXL","칩렛","첨단 패키징","추론","파운드리","2nm","3nm","5nm","TOPS","TOPS/W"];
const STOP=new Set(["관련","대한","위한","통해","이번","최근","발표","전망","동향","시장","기업","기술","그리고","에서","으로","한다","했다","밝혔다","news"]);
const METRIC=/(?:약\s*)?(?:\d{1,3}(?:,\d{3})+|\d+(?:\.\d+)?)\s*(?:%|조원|억원|만원|원|억\s*달러|만\s*달러|달러|usd|배|대|개|건|tops(?:\/w)?|w|nm|gb\/s|tb\/s)/gi;
function clean(v:string){return v.replace(/&nbsp;|&#160;|\u00a0/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function textOf(s:TrendSource){return `${s.title} ${s.excerpt||""} ${(s.content||"").slice(0,30000)}`}
function sentences(v:string){return clean(v).split(/(?<=[.!?。]|다\.)\s+/).map(clean).filter(s=>s.length>=28&&s.length<=360)}
function tokens(v:string){return new Set(v.toLocaleLowerCase("ko").replace(/[^0-9a-z가-힣]+/g," ").split(/\s+/).filter(w=>w.length>1&&!STOP.has(w)))}
function overlap(a:Set<string>,b:Set<string>){if(!a.size||!b.size)return 0;return [...a].filter(w=>b.has(w)).length/Math.min(a.size,b.size)}
function matches(list:string[],v:string){const lower=v.toLocaleLowerCase("ko");return [...new Set(list.filter(x=>lower.includes(x.toLocaleLowerCase("ko"))))]}
function classify(s:TrendSource):TrendCategory{if(s.categoryHint)return s.categoryHint;const title=s.title.toLowerCase(),excerpt=(s.excerpt||"").toLowerCase(),body=(s.content||"").slice(0,20000).toLowerCase();return (Object.keys(TERMS) as TrendCategory[]).map(category=>({category,score:TERMS[category].reduce((n,x)=>n+(title.includes(x)?4:0)+(excerpt.includes(x)?2:0)+(body.includes(x)?1:0),0)})).sort((a,b)=>b.score-a.score||(a.category==="market"?-1:1))[0].category}
function getMetrics(s:TrendSource){return [...new Set(textOf(s).match(METRIC)||[])].slice(0,10)}
function uniqueRows(rows:TrendSource[]){const kept:TrendSource[]=[];for(const row of rows){const duplicate=kept.some(item=>(row.url&&item.url&&row.url.replace(/[?#].*$/,"")===item.url.replace(/[?#].*$/, ""))||overlap(tokens(row.title),tokens(item.title))>=.72);if(!duplicate)kept.push(row)}return kept}
function related(group:TrendSource[],row:TrendSource){const candidate=textOf(row), companies=new Set(matches(COMPANIES,candidate).map(v=>v.toLowerCase())), tech=new Set(matches(TECHNOLOGIES,candidate).map(v=>v.toLowerCase()));return group.some(item=>{const score=overlap(tokens(item.title),tokens(row.title)), itemCompanies=new Set(matches(COMPANIES,textOf(item)).map(v=>v.toLowerCase())), itemTech=new Set(matches(TECHNOLOGIES,textOf(item)).map(v=>v.toLowerCase()));const sharedCompany=[...companies].some(v=>itemCompanies.has(v)),sharedTech=[...tech].some(v=>itemTech.has(v));return score>=.38||(sharedCompany&&sharedTech)||(sharedCompany&&score>=.2)})}
function facts(group:TrendSource[],category:TrendCategory){const focus=tokens(group.map(r=>r.title).join(" "));const ranked=group.flatMap(row=>sentences(row.content||row.excerpt||"").map(sentence=>({sentence,score:overlap(tokens(sentence),focus)*10+TERMS[category].filter(term=>sentence.toLowerCase().includes(term)).length+(sentence.match(METRIC)?1:0)}))).sort((a,b)=>b.score-a.score);const picked:string[]=[];for(const item of ranked){if(picked.some(v=>overlap(tokens(v),tokens(item.sentence))>=.62))continue;picked.push(item.sentence);if(picked.length===3)break}return picked}
function issue(group:TrendSource[],category:TrendCategory,index:number):TrendIssue{const combined=group.map(textOf).join(" "),companies=matches(COMPANIES,combined).slice(0,6),technologies=matches(TECHNOLOGIES,combined).slice(0,6),metrics=[...new Set(group.flatMap(getMetrics))].slice(0,10),selected=facts(group,category),subject=[companies[0],technologies[0]].filter(Boolean).join("·")||"해당 이슈",basis=group.length>1?`${group.length}개 출처에서 공통으로 확인되는 흐름이다.`:"현재는 단일 출처에서 확인되는 초기 신호다.",summary=clean(selected[0]||group[0].excerpt||group[0].title).slice(0,240),introduction=`${subject} 관련 움직임은 ${LABELS[category]}을 판단하는 주요 단서다. ${basis} 사건의 배경과 구체적 움직임, 수치, 기업·기술 간 연결을 나누어 살펴본다.`,body=selected.length?selected.map((value,n)=>`${n+1}) ${value}`).join(" "):`1) ${group[0].excerpt||group[0].title}`,connections=[companies.length?`관련 기업은 ${companies.join("·")}`:"",technologies.length?`연결 기술은 ${technologies.join("·")}`:""].filter(Boolean).join("이며, "),implications=`${technologies.length?`${technologies.join("·")}의 성능·효율·배포 가능성이 실제 벤치마크와 도입 결과에서 입증되는지가 기술 경쟁력을 가른다.`:"모델 성능과 배포 효율, 윤리·법적 위험을 함께 충족하는지가 시장 확산을 좌우한다."} ${companies.length?`${companies.join("·")}의 움직임은 국내 산업의 공급망과 컴퓨팅 기반 경쟁에 직접 영향을 미친다.`:"해당 변화는 국가 산업경쟁력과 시장 접근성에 영향을 미치는 변수다."} ${group.length>1?"다중 출처에서 반복 확인됐으나 수치의 기준 시점과 범위는 원문 대조가 필요하다.":"단일 출처 신호이므로 후속 근거 확보 전에는 확정적 추세로 해석하지 않는다."}`;const representative=[...group].sort((a,b)=>a.title.length-b.title.length)[0].title.replace(/\s*[-|｜]\s*[^-|｜]{2,20}$/,""),headline=companies.length&&technologies.length?`${companies[0]}의 ${technologies[0]} 관련 움직임과 파급효과`:representative;return{id:`${category}-${index}`,headline,summary,introduction,body,implications,metrics,companies,technologies,sources:group.map(r=>{let publisher="모아";try{publisher=r.url?new URL(r.url).hostname.replace(/^www\./,""):"모아"}catch{}return{id:r.id,title:r.title,url:r.url,origin:r.origin||"MOA",createdAt:r.createdAt,publisher}})}}
function cluster(rows:TrendSource[],category:TrendCategory){const groups:TrendSource[][]=[];for(const row of rows){const target=groups.find(g=>related(g,row));if(target)target.push(row);else groups.push([row])}return groups.map((g,i)=>issue(g,category,i))}
function chapter(number:number,title:string,lead:string,items:TrendIssue[]){return{number,title,lead,sections:items.map(item=>({title:item.headline,claim:item.summary,analysis:`${item.introduction} ${item.body}`,implications:item.implications,metrics:item.metrics,sources:item.sources}))}}

export function buildTrendReport(inputRows:TrendSource[],period:"week"|"month"){
 const rows=uniqueRows(inputRows),categorized:Record<TrendCategory,TrendSource[]>={technology:[],market:[],company:[],policy:[]};rows.forEach(r=>categorized[classify(r)].push(r));
 const sections:Record<TrendCategory,TrendIssue[]>={market:cluster(categorized.market,"market"),company:cluster(categorized.company,"company"),policy:cluster(categorized.policy,"policy"),technology:cluster(categorized.technology,"technology")};
 const issues=Object.values(sections).flat(),issueCount=issues.length,allMetrics=[...new Set(issues.flatMap(i=>i.metrics))].slice(0,15),allCompanies=[...new Set(issues.flatMap(i=>i.companies))].slice(0,6),allTechnologies=[...new Set(issues.flatMap(i=>i.technologies))].slice(0,6),leading=(Object.keys(sections) as TrendCategory[]).sort((a,b)=>sections[b].length-sections[a].length)[0],periodLabel=period==="week"?"주간":"월간",generatedAt=new Date().toISOString();
 const overview=rows.length?`분석 기간의 자료 ${inputRows.length}건에서 중복 기사를 제거하고 ${rows.length}건을 선별한 뒤, 서로 연결되는 내용을 ${issueCount}개 이슈로 통합했습니다. 핵심 흐름은 ${LABELS[leading]}에 집중되어 있으며, 개별 기사보다 반복 확인된 사실과 기업·기술의 연결 관계를 중심으로 재구성했습니다.`:"분석 기간에 보고서로 구성할 자료가 없습니다.";
 const overviewBullets=rows.length?[`작성일자: ${generatedAt.slice(0,10).replace(/-/g,".")}`,`문제 맥락: AI 기술·시장 변화가 국내 산업 경쟁력과 정책 실행에 미치는 영향을 파악한다.`,`성공 기준: 최근성·수치·실제 URL을 갖춘 근거로 기술 및 정책 대안을 제시한다.`,`통합 결과: 원자료 ${inputRows.length}건 → 중복 제거 ${rows.length}건 → 핵심 이슈 ${issueCount}개`,`이슈 분포: 시장 ${sections.market.length}개 · 기업 ${sections.company.length}개 · 정책 ${sections.policy.length}개 · 기술 ${sections.technology.length}개`,allCompanies.length?`주요 기업: ${allCompanies.join(" · ")}`:"주요 기업 정보는 추가 확인 필요",allTechnologies.length?`연결 기술: ${allTechnologies.join(" · ")}`:"연결 기술 정보는 추가 확인 필요"]:["해당 기간에 분석할 자료가 없습니다."];
 const sectionSummaries=Object.fromEntries((Object.keys(sections) as TrendCategory[]).map(c=>[c,sections[c].length?`${categorized[c].length}건의 자료를 ${sections[c].length}개 이슈로 통합했습니다. 같은 사건을 반복 나열하지 않고 공통 사실과 차이를 함께 정리합니다.`:"해당 기간에 확인된 이슈가 없습니다."])) as Record<TrendCategory,string>;
 const chapters=[
  chapter(1,"분석 범위와 시장 구조","시장 정의와 수치의 범위를 구분하고, 최근 수요·투자·지역별 흐름을 하나의 구조로 해석한다.",sections.market),
  chapter(2,"주요 기업의 경쟁 구도","빅테크·중국·국내 기업의 제품, 도입, 파트너십, 투자 움직임을 경쟁 축별로 비교한다.",sections.company),
  chapter(3,"기술 발전과 워크로드 전환","모델·하드웨어·오픈소스의 변화가 성능, 전력 효율, 배포 경제성에 미치는 영향을 분석한다.",sections.technology),
  chapter(4,"정책·규제와 산업 기반","국내외 법·예산·규제가 시장 접근성과 공급망, 국가 경쟁력에 미치는 효과를 검토한다.",sections.policy),
  chapter(5,"종합 판단과 실행 전략","기술 가능성과 산업정책 실행 가능성을 함께 고려해 후속 관찰 및 대응 방향을 제시한다.",issues.slice(0,6)),
 ];
 const caveats=["발표 성능보다 실제 배포 환경의 성능·전력·비용과 소프트웨어 전환비용이 시장경쟁력을 결정한다.","단순 지원 규모보다 국내 기업의 수주·양산·반복매출로 이어지는 수요와 공급망 연결이 산업성과를 좌우한다.","글로벌 도입 사례와 시장 수요를 국내 기술개발·인재·컴퓨팅 기반에 연결하는 실행력이 향후 경쟁 격차를 만든다."];
 const monitoring=["기업 도입 발표가 실제 공급계약과 반복매출로 전환되는지 분기별로 확인","동일 워크로드 기준 성능/와트·지연시간·총소유비용을 독립 자료로 비교","정책 예산의 집행률과 국내 제품 구매·조달 성과를 함께 측정","시장 전망치는 정의와 기준 시점이 같은 자료끼리만 비교"];
 const md=[`# AI·NPU ${periodLabel} 이슈 중심 종합 보고서`,"",`## ■ 전체 내용 요약 (${generatedAt.slice(0,10).replace(/-/g,".")})`,"",overview,"",...overviewBullets.map(x=>`- ${x}`)];if(allMetrics.length)md.push("","### 핵심 수치","",...allMetrics.map(x=>`- ${x}`));for(const [n,c] of (Object.keys(sections) as TrendCategory[]).entries()){md.push("",`## ${n+1}. ${LABELS[c]}`,"",sectionSummaries[c]);for(const i of sections[c]){md.push("",`### ${i.headline}`,"",`- ${i.summary}`,`  - ${i.introduction} ${i.body}`,"",`**시사점:** ${i.implications}`);if(i.metrics.length)md.push("",`**비교 수치:** ${i.metrics.join(" · ")}`);for(const s of i.sources.slice(0,3)){const date=(s.createdAt||"").slice(0,10).replace(/-/g,".");md.push("",`> 출처 : [${s.title}(${s.publisher}, ${date})](${s.url||`/source/${s.id}`})`)}}}md.push("","---","","## 관련근거 및 출처","");const evidence=[...new Map(issues.flatMap(i=>i.sources).map(s=>[s.url||String(s.id),s])).values()];for(const s of evidence){const date=(s.createdAt||"").slice(0,10).replace(/-/g,".");md.push(`- [${s.title}(${s.publisher}, ${date})](${s.url||`/source/${s.id}`})`)}
 const chapterMd=[`# AI·NPU ${periodLabel} 종합 동향 보고서`,"",`## ■ 전체 내용 요약 (작성일자: ${generatedAt.slice(0,10).replace(/-/g,".")})`,"",overview,"",...overviewBullets.map(x=>`- ${x}`)];
 for(const ch of chapters){chapterMd.push("",`## ${ch.number}. ${ch.title}`,"",ch.lead);for(const section of ch.sections){chapterMd.push("",`### ${section.title}`,"",`- ${section.claim}`,`  - ${section.analysis.slice(0,600)}`,"",`**시사점:** ${section.implications}`);for(const source of section.sources.slice(0,3)){const date=source.createdAt.slice(0,10).replace(/-/g,".");chapterMd.push("",`> 출처 : [${source.title}(${source.publisher}, ${date})](${source.url||`/source/${source.id}`})`)}}
 }
 chapterMd.push("","## 6. 시사점 및 향후 전망","",...caveats.map(x=>`- ${x}`),"",...monitoring.map(x=>`- ${x}`),"","---","","## 관련근거 및 출처","");const allEvidence=[...new Map(issues.flatMap(i=>i.sources).map(s=>[s.url||String(s.id),s])).values()];for(const source of allEvidence){const date=source.createdAt.slice(0,10).replace(/-/g,".");chapterMd.push(`- [${source.title}(${source.publisher}, ${date})](${source.url||`/source/${source.id}`})`)}
 return{period,periodLabel,generatedAt,overview,overviewBullets,sectionSummaries,total:inputRows.length,uniqueTotal:rows.length,issueCount,allMetrics,sections,chapters,caveats,monitoring,markdown:chapterMd.join("\n")};
}
